# Generated by Django 5.0.2 on 2024-03-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='qnt',
            field=models.IntegerField(null=True),
        ),
    ]
