# Generated by Django 5.0.2 on 2024-03-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_item_qnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
