# Generated by Django 5.0.2 on 2024-03-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_item_key3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_details',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='0', max_length=100)),
                ('date_time', models.DateTimeField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField()),
            ],
        ),
    ]
