# Generated by Django 5.0.2 on 2024-03-08 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_item_details_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_details',
            old_name='item_id',
            new_name='item',
        ),
    ]
